steps:
  # Step 1: Clean and install dependencies using Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']

  # Step 2: Deploy the application to App Engine using Maven
  - name: 'gcr.io/cloud-builders/mvn'
<<<<<<< HEAD
    args: ['appengine:deploy', '-DskipTests']
=======
    args: ['appengine:deploy']

  # - name: 'gcr.io/cloud-builders/mvn'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       ./mvnw -DskipTests package appengine:deploy

>>>>>>> 52699f0c51919b01017de7ffd6ba548e4a11b698
