steps:
  # Step 1: Clean and install dependencies using Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']

  # Step 2: Deploy the application to App Engine using Maven
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
<<<<<<< HEAD
        ./mvnw -DskipTests package appengine:deploy
=======
        ./mvnw -DskipTests package appengine:deploy
>>>>>>> e4038f84af0b1a87673cabd3cdd41d1afadc31c1
