steps:
  # Step 1: Clean and install dependencies using Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']

  # Step 2: Deploy the application to App Engine using Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['appengine:deploy', '-DskipTests']